### ISSUE TITLE
Error when build project

### ISSUE THREAD

**Issue by meodemsao** [rgab1508/OpenStore#4]
When build project, i have error message 

```ModuleNotFoundError: Module not found: Error: Can't resolve '../config' in 'C:\Users\bangvu\Desktop\Labs\OpenStore\pages'

> Build error occurred
Error: > Build failed because of webpack errors
    at C:\Users\bangvu\Desktop\Labs\OpenStore\node_modules\next\dist\build\index.js:397:19
    at async Span.traceAsyncFn (C:\Users\bangvu\Desktop\Labs\OpenStore\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async Object.build [as default] (C:\Users\bangvu\Desktop\Labs\OpenStore\node_modules\next\dist\build\index.js:77:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openstore@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openstore@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bangvu\AppData\Roaming\npm-cache\_logs\2021-11-15T14_51_29_261Z-debug.log
```

I find in ```pages/create```, and i think we miss config file 

```import { nftaddress, nftmarketaddress } from "../config";```

I want to ask how we create ```nftaddress, nftmarketaddress``` constants
p/s: I try created account in https://infura.io/ but i can't find two contants above

**Comment by adiunni** [comment]
Have you created a project in Infura ? You must have received a URL for JSON RPC provider. Use the URL to add in `hardhat.config.js` file (follow the format mentioned in the file). Make sure to add private key in a `.secret` file. Private key can be imported from Metamask account.

Create a `config.js` file to store `nftaddress` and `nftmarketaddress` which you will receive after deploying the contracts to the network of your choice. Refer image below (**DO NOT COPY THE ADDRESS. USED FOR LOCAL NODES ONLY**)
![config.js file](https://user-images.githubusercontent.com/61608668/141809536-58e8dcf1-7e54-4c97-8b5d-e35d833cb619.jpeg)
 
To deploy the contracts in your network just type `npx hardhat run scripts/deploy.js --network <network of your choice>` and hit enter. A sample is demonstrated below.
![Screenshot 2021-11-15 at 21 09 18](https://user-images.githubusercontent.com/61608668/141810218-a4b4dc0a-108e-4f7b-b260-bb5d5b58cafe.png)
Change `localhost` if deploying to another network.
Two hash values will be returned and add the following values (**nft** value in `nftaddress` and **nftMarke**t value in `nftmarketaddress` in config.js file)

**Comment by adiunni** [comment]
In `hardhat.config.js` file, follow the structure mentioned below. Make sure to add a private key in `.secret` file and your infura ID in `.infuraId` file.

```
module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {
      chainId: 1337,
    },
    mumbai: {
      // Infura
      url: `https://polygon-mumbai.infura.io/v3/${infuraId}`,
      accounts: [privateKey],
    },
  },
  solidity: {
    version: "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
};
```

**Comment by rgab1508** [comment]
first you need to deploy with hardhat
